FROM openjdk:8

RUN apt update && apt install rsync wget -y

# 로그 폴더 생성
RUN mkdir -p /data/indexerLog

RUN chmod 777 -R /data

ENV spring_logging_level=debug
ENV LANG=ko_KR.euckr

ARG VERSION

COPY lib/Altibase.jar .
COPY target /app

WORKDIR /app

EXPOSE 9350
EXPOSE 8080
EXPOSE 9100

CMD ["java", "-Dlogback.configurationFile=logback-prod.xml", "-Dfile.encoding=utf-8", "-classpath", "indexer-${VERSION}.jar:Altibase.jar", "org.springframework.boot.loader.JarLauncher"]
